### ISSUE TITLE
Feature: command(s) for inserting/deleting #_ ignore forms

### ISSUE THREAD

**Issue by yuhan0** [clojure-emacs/clojure-mode#567] opened 2020-04-25 16:32 UTC
It would be useful to have some convenient way of inserting/deleting #_ forms built into clojure-mode, but its implementation may depend on personal preference. I hope this issue attracts some discussion as to what would suit the majority of users.

My personal implementation of this idea can be found here, which I've been tweaking over the past year: https://gist.github.com/yuhan0/38ac43c764017917fc3f3e5dc9104f1b
There are two interactive commands defined there,  `clojure-toggle-ignore-form` and `clojure-toggle-ignore-surrounding-form`- see docstrings for their usage.

I made some usability choices in the way it interprets numeric and universal arguments, and there's some degree of DWIM by wrapping an active region in `(comment)` forms and inserting blank lines before top-level forms to reduce diffs.

But it's clear that this may not suit everyone, in particular see 
https://github.com/dotemacs/clojure-comment-dwim.el/issues which takes a more DWIM approach with a single entry point and more logic to determine what the command should do in different contexts and when repeatedly called.

See also https://github.com/BetterThanTomorrow/calva/issues/505
for another interpretation of what such a command may do in different scenarios (note it's more selection-based as VSCode doesn't have numeric command arguments)

**Comment by bbatsov** [comment] 2020-04-25 16:47
I'm fine with adding something along those lines. My preference would be to have something operating on the current top-level form and the current/preceding form. I'm fine with a toggling behaviour for those commands. As for regions - I'm not sure they make a lot of sense for a command of that nature, you might not have selected a complete form.

**Comment by dotemacs** [comment] 2020-04-25 23:03
My thinking is that since we're using s-expressions, we can be smart about it, the way paredit & smartparens modes are about navigation, slurping, barfing and so on, but in regards to commenting.

> My preference would be to have something operating on the current top-level form and the current/preceding form. 

I've already got that implemented.

For example, I handle commenting out the current s-expression, or with a prefix argument, PREFIX s-expressions above.

>  I'm fine with a toggling behaviour for those commands.

Cool, I've got that in too.

> As for regions - I'm not sure they make a lot of sense for a command of that nature, you might not have selected a complete form.

I handle that also. 

For example, if you've selected a whole s-expression, as a region, then the mode would comment it out with a `#_` at the start of the selected region. But if your selected region is not a s-expression, then it would wrap the region in `(comment ...)`.

It also toggles (un)commenting, depending on how is the particular point/region (un)commented.

I tried to get some clarification on the current behaviour here: https://github.com/dotemacs/clojure-comment-dwim.el/issues/2

See the master branch of: https://github.com/dotemacs/clojure-comment-dwim.el

**Comment by andreyorst** [comment] 2020-09-28 09:41
Isn't this a duplicate of #411 ?

**Comment by yuhan0** [comment] 2021-02-18 08:53
I'll submit a PR with my above code, removing the `(comment` behaviour on regions and adding an additional command `clojure-toggle-ignore-defun` for top-levvel forms, hope that's ok!

**Comment by bbatsov** [comment] 2021-02-18 09:20
Yep, that's fine.

**Closed** 2021-02-26 13:36 UTC
Labels: feature request
