### ISSUE TITLE
Allow single semicolon comments on a line

### ISSUE THREAD

**Issue by jeaye** [clojure-emacs/clojure-mode#516] opened 2019-03-17 03:06 UTC
## Expected behavior
Single semicolon comments can be on their own line without messing up the indentation.

This was originally reported to SO [here](https://stackoverflow.com/questions/4531761/comment-indenting-seems-messed-up-in-clojure-mode) in 2010. I recognize that the [recommended Lisp style](https://github.com/bbatsov/clojure-style-guide#comments) is to have double semicolons for dedicated comment lines and single semicolons only for lines with code. **However**, even the core Clojure code and some of the most popular Clojure libraries have uses of single semicolons on dedicated lines ([clojure.core](https://github.com/clojure/clojure/blob/master/src/clj/clojure/core.clj#L5969-L5990), [cljs.core](https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/core.cljs#L1023-L1028), [instaparse](https://github.com/Engelberg/instaparse/blob/master/src/instaparse/transform.cljc#L48-L81)). So, I *implore* you to support this as a non-default option.

Furthermore, this is a pain point on my team at work, since some folks are in Emacs (using clojure-mode) and others are in Vim or IntelliJ where those semicolon indentation rules aren't a problem. The Clojure codebase was written before we had Emacs users on the team, so we have 15K+ lines of code using single semicolons and now the Emacs folks are having issues. We could change all of the code, but then everyone not using Emacs would need to change the way they write comments.

Concretely, applying indentation to a file containing this should not change anything (assuming this option is enabled):

```clojure
; See below.
(defn foo []
  ; Wow, cool!
  (println "cool"))
```

## Actual behavior
There is no configuration for this, so it's not currently possible to support. Lines containing single semicolon comments get indented by huge amounts when applying indentation to the line, range, form, or file.

Following the concrete example, the file becomes:

```clojure
                                        ; See below.
(defn foo []
                                        ; Wow, cool!
  (println "cool"))
```

## Steps to reproduce the problem
Create a new file in Clojure mode, add a single semicolon comment, like:

```clojure
; uh oh!
```

and then apply indentation to the line or file (by pressing `Tab` or `Enter`, for example). The line will be indented a huge amount, rather than left exactly as it was. This also applies to evil mode (hitting `==`, for example).

### clojure-mode version information
This returned `nil` for me. I'm using Spacemacs, which may be interfering here. I'm a Vim user, primarily, but trying to do my best to repro.

```
clojure-mode (version nil)
```

### Emacs version

`26.1`

### Operating system
This has been reproduced on:

* Arch Linux
* Ubuntu Linux
* macOS

**Comment by bbatsov** [comment] 2019-03-20 20:32
I'm aware of the problem, but unfortunately this requires significant changes that I don't have time to do myself right now. 

The core of the problem is that `clojure-mode` uses a lot of code straight from `lisp-mode` and that's code is kind of hard to change, without us just duplicating it. If it wasn't for this I would have added this config option long ago. 

I'd gladly merge a PR if someone decides to tackle this.

**Comment by bbatsov** [comment] 2019-03-20 20:34
Just noticed I created a task for me regarding this over 4 years ago. (https://github.com/clojure-emacs/clojure-mode/issues/270) Long standing problem indeed.

**Comment by yuhan0** [comment] 2019-03-22 07:59
Doesn't seem to be that big of a change - here's the relevant code adapted from `lisp-indent-line` minus special handling for comments and spliced in place into `clojure-indent-line`

```elisp
(defun clojure-indent-line ()
  "Indent current line as Clojure code."
  (interactive)
  (if (clojure-in-docstring-p)
      (save-excursion
        (beginning-of-line)
        (when (and (looking-at "^\\s-*")
                   (<= (string-width (match-string-no-properties 0))
                       (string-width (clojure-docstring-fill-prefix))))
          (replace-match (clojure-docstring-fill-prefix))))

    ;; `lisp-indent-line', but without special handling of comments
    (let ((pos (- (point-max) (point)))
          (indent (progn (beginning-of-line)
                         (calculate-lisp-indent (lisp-ppss)))))
      (when indent (indent-line-to indent))
      ;; If initial point was within line's indentation,
      ;; position after the indentation.  Else stay at same point in text.
      (if (> (- (point-max) pos) (point))
	        (goto-char (- (point-max) pos))))))
```

You might also want to change the value of `comment-indent-function` and `comment-add` in clojure buffers:
```elisp
(add-hook 'clojure-mode-hook
          (lambda ()
            (setq comment-indent-function 'comment-indent-default)
            (setq comment-add 0)
            (comment-normalize-vars)))
```

I could open a PR for the above but it's not clear what the defaults should be, or if there should be some sort of configuration toggle? 
It does seem like the 1-semicolon style is pretty common in the wild, and in clojure core libs.

**Comment by bbatsov** [comment] 2019-03-22 10:51
Well, the default should be what it has always been, as it's generally a bad idea to change something that has been the default since day 1. 

Generally we need some toggle - "clojure-semantic-comments" that's true by default.

> Doesn't seem to be that big of a change - here's the relevant code adapted from lisp-indent-line minus special handling for comments and spliced in place into clojure-indent-line

But I think your change will break other commands relying on the current behavior - e.g. the various insert comment at point commands that Emacs has. Anyways, I'm glad you've decided to tackle this, but you should be careful as the behavior from lisp-mode trickles down to many places and we don't want to break something big. 

>                          (calculate-lisp-indent (lisp-ppss)))))

I'd prefer it if we copied those functions as well and tweaked them for Clojure if needed, so we can achieve true separation. I'm not sure how much code it's reasonable to share with lisp-mode, my preference would be as little as possible, but I don't have time to dwell on this much.

**Comment by yuhan0** [comment] 2019-03-22 16:46
Thanks for the reply - what I'll do (and welcome others to) is probably use this change in my local config for the next couple of days or weeks and see if it breaks anything else.
Do you have any hunch on what sort of places this change might trickle down to? It seemed pretty self-contained but I'm not at all familiar with all the intricacies of `lisp-mode`.

>                      (calculate-lisp-indent (lisp-ppss)))))

I had a peek at that function but it's a huge 150-line body with other nested calls and what looks like plenty of mutable state to untangle - probably the sort of thing that's best left untouched :p

**Comment by bbatsov** [comment] 2019-03-23 10:57
> Do you have any hunch on what sort of places this change might trickle down to? It seemed pretty self-contained but I'm not at all familiar with all the intricacies of lisp-mode.

You and me both. :D Nothing comes to mind expect commands like `M-;`, but I guess those should be easy to get right. 

Let's go with your idea and see how well it will work.

**Comment by bbatsov** [comment] 2019-03-31 10:37
@yuhan0 Any progress with this?

**Comment by yuhan0** [comment] 2019-04-01 08:42
Hi, thanks for the follow up - I've been using the above change for more than a week now and noticed nothing out of the ordinary :)

(It actually helped fix a bug in my personal config, where I had bound `indent-sexp` to a custom key, not knowing that it was a `lisp-mode` specific command - the standard binding `C-M-q` is bound to `prog-indent-sexp` in clojure-mode which behaves as expected.)

**Comment by Frozenlock** [comment] 2019-04-16 20:52
I tried `clojure-indent-line` as provided by @yuhan0 but it breaks in my Emacs once I press tab to indent:
```
calculate-lisp-indent: Symbol’s function definition is void: lisp-ppss
```

**Comment by yuhan0** [comment] 2019-04-17 06:18
Hmm, turns out that was something added relatively recently in Emacs 26: 
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=4713dd425beac5cb459704e67dcb8f6faf714375

I assume you're using an older version of Emacs, It should work if you simply remove the `(lisp-ppss)` form and use the 0-argument call to `calculate-lisp-indent`.

**Comment by Frozenlock** [comment] 2019-05-08 14:55
Any news on this? If the problem is harder than expected, I could move to Emacs 26 and tried the patch mentioned above.

**Comment by bbatsov** [comment] 2019-05-08 15:14
I've been super busy lately and I dropped the ball on this. It's not super complex, but I need to find some time for it.

**Comment by jeaye** [comment] 2019-05-08 18:57
Another report: one of my teammates has been using @yuhan0's approach with no issue. Naturally, he's on a newer Emacs, but it seems to work well for those who are!

**Comment by Frozenlock** [comment] 2019-05-11 19:11
Upgraded to Emacs 26.2 and it does indeed work.
I'll use this until it can be officially toggled in `clojure-mode`. 
Thank you very much!

**Comment by j-cr** [comment] 2019-12-27 20:00
By the way, this can be fixed without modifying any code, just call this in your clojure-mode hook:

    (setq-local comment-column 0)

`clojure-mode-variables` sets it to 40 by default

**Comment by svantevonerichsen6906** [comment] 2020-01-07 08:31
I believe that setting comment-column to 0 is the right solution for a legacy codebase that one doesn't want to change, instead of codifying nonstandard comment styles.

**Comment by bbatsov** [comment] 2020-04-19 06:05
@yuhan0 Btw, can you look into this one as well? You've been on a roll lately and it'd be nice to include this in the next release. I might eventually find time to revisit this myself, but for the next couple of weeks my focus is mostly nREPL and cider-nrepl.

**Comment by yuhan0** [comment] 2020-04-19 08:32
I actually found that @j-cr 's above solution of setting `comment-column` was the simplest way around the issue, and works on a project-specific basis with dir-local variables. So it seems right to just add a note about this to the docs instead of tampering with lisp-mode indentation code and introducing more configuration vars.

**Comment by bbatsov** [comment] 2020-04-19 08:42
That's fine by me. I was struggling to decide whether it's best to do this or to continue decoupling things from `lisp-mode`.

**Closed** 2020-04-19 09:37 UTC
Labels: enhancement, help wanted

**Comment by qleguennec** [comment] 2020-09-23 15:23
I'm having an issue with this as well, because `(setq-local comment-column 0)` actually still messes with the indentation in the case where the comment is already indented. It indents it to 0.
