### ISSUE TITLE
Weird syntax highlighting in the word `factory`

### ISSUE THREAD

**Issue by anmonteiro** [clojure-emacs/clojure-mode#369] opened 2016-03-05 15:13 UTC
clojure-mode v 5.2.0

As you can see in the screenshot below, the `ory` part of the word becomes white when calling a function named `factory`
<img width="200" alt="screen shot 2016-03-05 at 16 11 22" src="https://cloud.githubusercontent.com/assets/661909/13548295/25cea2fc-e2ed-11e5-8b34-de06334608e5.png">

**Comment by Malabarba** [comment] 2016-03-06 22:07
I can't reproduce that here. I noticed you're using some form of colorized parentheses. Could you try disabling that mode to see if it's not the cause?

**Comment by anmonteiro** [comment] 2016-03-07 00:03
still the same behavior without rainbow-delimiters-mode
<img width="261" alt="screen shot 2016-03-07 at 00 55 05" src="https://cloud.githubusercontent.com/assets/661909/13558249/4456982e-e400-11e5-9995-1c1f4ad15508.png">

However, I launched `emacs -Q` and loaded only `clojure-mode` and didn't seem to see the issue.
Suppose it's safe to say it's not a `clojure-mode` problem, then?  maybe something with my theme?

**Comment by Malabarba** [comment] 2016-03-07 00:11
> Suppose it's safe to say it's not a clojure-mode problem, then? 

Yes.

> maybe something with my theme?

Unlikely. It's more likely to be some other mode. Does this only happen when cider is connected? Or does it happen as soon as you visit the file?
Also, try hitting `C-u C-x =` with point in the word `fact`. This will give a big buffer describing the character, and will tell you the name of the face being put there.

**Comment by bbatsov** [comment] 2016-03-07 05:58
Likely something to do with `midje`. I recall it had some minor-mode. (tests there are called facts)

**Comment by anmonteiro** [comment] 2016-03-07 12:33
> Does this only happen when cider is connected? Or does it happen as soon as you visit the file?

As soon as I visit the file

> Also, try hitting  `C-u C-x =` with point in the word `fact`

`fact` ->  `font-lock-keyword-face`
`ory` -> no face

> Likely something to do with `midje`.

I don't use `midje`.

**Comment by Malabarba** [comment] 2016-03-15 14:27
My only suggestion is to play around with your minor modes, see if any of them seems to be causing this. Unfortunately, font lock issues are very annoying to debug. 

I believe there's a package that helps pinpoint what font-lock rules are being applied to a specific symbol, but I can't recall the name.

**Comment by bbatsov** [comment] 2016-03-17 06:10
I'll close this one as it's definitely not a problem with `clojure-mode` itself.

**Closed by bbatsov** 2016-03-17 06:10 UTC
