### ISSUE TITLE
Single quote ' within identifier should have similar syntax highlighting to question mark ? within identifier

### ISSUE THREAD

**Issue by tclamb** [clojure-emacs/clojure-mode#454] opened 2017-10-15 18:27 UTC
```
(defn who's-on-first? []
  false)
```

should highlight as the def's varname
```
who's-on-first?
```

but instead only highlights
```
who
```

---

I don't know much emacs-lisp or anything about emacs packages, but I think adding another entry in this table for `?'` would do the trick. I'd be happy to open a pull request if so.

https://github.com/clojure-emacs/clojure-mode/blob/35f5d71b196b1a4b147a56a82b723d0383cb7282/clojure-mode.el#L302

**Comment by vspinu** [comment] 2017-10-16 15:09
Duplicate of  #435. Related to #290.

**Comment by bbatsov** [comment] 2017-10-31 08:13
Indeed. Join the discussions there - basically that's much harder to do than it seems.

**Closed by bbatsov** 2017-10-31 08:13 UTC
