### ISSUE TITLE
ugly format for `cond'

### ISSUE THREAD

**Issue by Kejia** [clojure-emacs/clojure-mode#324] opened 2015-09-25 18:34 UTC
```
(defn foo
  [a]
  (cond
    (and (sequential? a)
         (seq a)) (map inc a)
         (number? a) (inc a)
         :else (str ">>" a)))
```

**Comment by expez** [comment] 2015-09-26 08:11
Duplicate of https://github.com/clojure-emacs/clojure-mode/issues/296

**Closed** 2015-09-28 18:52 UTC
