### ISSUE TITLE
Support #_#_ highlighting

### ISSUE THREAD

**Issue by WorldsEndless** [clojure-emacs/clojure-mode#528] opened 2019-06-18 14:06 UTC
Syntax highlighting supports #_ form commenting; it would be excellent if it supported the stackable version of the same (e.g. `#_#_` comments out the next 2 forms, which is what the compiler sees) 
 
## Expected behavior
`#_#_` syntax highlights the next two forms as commented

## Actual behavior
`#_#_` has the same effect as `#_`, only highlighting one form.

## Steps to reproduce the problem
In a clj[s] buffer, type `#_` before a key in `{:key 'val}` and `:key` is highlighted as a comment. However, `#_#_` should also highlight `'val` as a comment, but it does not. 
 
GNU Emacs 26.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.4)
clojure-mode (version 5.11.0-snapshot)

OpenSUSE Linux Tumbleweed

**Comment by kommen** [comment] 2019-08-05 22:26
This is a duplicate of #404

**Comment by kommen** [comment] 2019-12-08 10:31
I think this can be closed now that https://github.com/clojure-emacs/clojure-mode/pull/545 has been merged.

**Closed** 2019-12-08 11:28 UTC
